name: urnicar
description: "Carski FRI urnik manager"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  kalender: ^0.14.3
  http: ^0.13.0
  html: ^0.15.0
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4
  hive_ce_generator: ^1.10.0
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true
